my webapp project:
  stage:  build
  image:  node
  script:
    - npm install express
    - node server.js  &
    - sleep 5 
    - echo "welcome to dbots..."  
    - curl  http://localhost:3000/data  | grep -i dbots
